### ISSUE TITLE
PDO MySQL SSL Error

### ISSUE THREAD

**Issue by schmittjoh** [heroku/heroku-buildpack-php#209]
With the latest PHP 7.1 version (7.1.1 and also 7.1.0), we are running into an SSL error in connection with a secure MySQL connection. Initial research suggests this to be an issue with the OpenSSL version that is being used, we do not see this locally:

```
2017-01-23T09:29:54.175674+00:00 app[web.1]: [23-Jan-2017 09:29:54 UTC] PHP Warning:  PDOStatement::execute(): SSL operation failed with code 1. OpenSSL Error messages:
2017-01-23T09:29:54.175760+00:00 app[web.1]: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length
2017-01-23T09:29:54.175903+00:00 app[web.1]: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91
2017-01-23T09:29:54.176052+00:00 app[web.1]: [23-Jan-2017 09:29:54 UTC] PHP Warning:  PDOStatement::execute(): MySQL server has gone away in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91
2017-01-23T09:29:54.176186+00:00 app[web.1]: [23-Jan-2017 09:29:54 UTC] PHP Warning:  PDOStatement::execute(): Error reading result set's header in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91
2017-01-23T09:29:55.568258+00:00 app[web.1]: [23-Jan-2017 09:29:55 UTC] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
2017-01-23T09:29:55.568276+00:00 app[web.1]: Stack trace:
2017-01-23T09:29:55.568337+00:00 app[web.1]: #0 /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
2017-01-23T09:29:55.568483+00:00 app[web.1]: #1 /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(828): Doctrine\DBAL\Driver\PDOStatement->execute()
2017-01-23T09:29:55.568529+00:00 app[web.1]: #2 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(1808): Doctrine\DBAL\Connection->executeQuery('SELECT t0.id AS...', Array, Array)
2017-01-23T09:29:55.568677+00:00 app[web.1]: #3 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(1747): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->getOneToManyStatement(Array, Object(Model\User))
2017-01-23T09:29:55.568838+00:00 app[web.1]: #4 /app/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2835): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadOneToManyCollection(Array, Object(Model\User), Object(Doctrine\ORM\PersistentCollection))
```

**Comment by schmittjoh** [comment]
I'm closing this here as it seems more appropriate as a PHP bug:
https://bugs.php.net/bug.php?id=73978

**Comment by dzuelke** [comment]
Pinged @bukka about this; looks like he's on it! :)
